allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - esbuild
  - prisma
  - unrs-resolver
