sonar.projectKey=nestjs-realworld
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=src/**/*.spec.ts,test/**/*.spec.ts
sonar.exclusions=src/generated/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.spec.ts,test/**/*.spec.ts,src/generated/**
sonar.cpd.exclusions=src/generated/**
