version: "3"

tasks:
  install:
    cmds:
      - pnpm i
  lint:
    cmds:
      - pnpm lint
  build:
    cmds:
      - pnpm prisma generate
      - pnpm build
  test:
    cmds:
      - pnpm prisma migrate deploy
      - pnpm test --coverage
