version: "3"

tasks:
  prepare:
    cmds:
      - corepack enable
      - corepack prepare pnpm@latest-9 --activate
      - pnpm config set store-dir .pnpm-store
  install:
    cmds:
      - pnpm i
  lint:
    cmds:
      - pnpm lint
  build:
    cmds:
      - pnpm prisma generate
      - pnpm build
  test:
    cmds:
      - pnpm prisma migrate deploy
      - pnpm test -- --coverage
