on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - uses: https://gitea.okami101.io/okami101/actions/task@main
        env:
          DATABASE_URL: postgres://test:test@postgres:5432/test
          JWT_SECRET: secret-key
      - name: Cache sonar
        uses: actions/cache@v4
        with:
          path: /opt/sonar-scanner/.sonar/cache
          key: ${{ runner.os }}-sonar
      - uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          gitea-token: ${{ secrets.RELEASE_TOKEN }}
          release: true
