on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - uses: https://gitea.okami101.io/okami101/actions/task@main
        env:
          DATABASE_URL: postgres://test:test@${{ vars.POSTGRESQL_HOST }}:5432/conduit_nestjs_test
          JWT_SECRET: secret-key
      - name: Cache sonar
        uses: actions/cache@v4
        with:
          path: /opt/sonar-scanner/.sonar/cache
          key: ${{ runner.os }}-sonar
      - uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          gitea-token: ${{ secrets.RELEASE_TOKEN }}
          release: true
